twig:
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'    
    file_name_pattern: '*.twig'
    autoescape: 'html'


when@test:
    twig:
        strict_variables: true
